#pragma checksum "C:\Users\liuzh\Source\Repos\ResourceGenerator\Opportunity.ResourceGenerator.TestApp\Strings\en\Resource.resJson" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "EDA3C600C89FF776C9797128AB0869CC"
#pragma checksum "C:\Users\liuzh\Source\Repos\ResourceGenerator\Opportunity.ResourceGenerator.TestApp\Strings\en\Resource.resw" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "E125E8B3C31232DF734190B5EC390910"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator.Generator", "1.0.0.0")]
    internal interface IResource : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>6</para>
        /// </summary>
#warning Resource has been renamed. ResourceName: "ha\"ha", PropertyName: "ha_ha"
        string ha_ha { get; }
#warning Resource has been renamed. ResourceName: "ha.h\"a2", PropertyName: "ha_h_a2"
        global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.Resource.Iha_h_a2 ha_h_a2 { get; }
        /// <summary>
        /// <para>1&#39;0</para>
        /// </summary>
        string _haha { get; }
        /// <summary>
        /// </summary>
#warning Resource has been renamed. ResourceName: "\t", PropertyName: "__"
        string __ { get; }
        global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.Resource.Itest test { get; }
        /// <summary>
        /// <para>Re</para>
        /// </summary>
        string Reset { get; }
        /// <summary>
        /// <para>MC</para>
        /// </summary>
        string MemberwiseClone { get; }
        /// <summary>
        /// <para>REq</para>
        /// </summary>
        string ReferenceEquals { get; }
        /// <summary>
        /// <para>GT</para>
        /// </summary>
        string GetType { get; }
        /// <summary>
        /// <para>GHC</para>
        /// </summary>
        string GetHashCode { get; }
        new global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.Resource.IGetValue GetValue { get; }
        global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.Resource.Idouble @double { get; }
        /// <summary>
        /// <para>A question mark?</para>
        /// </summary>
#warning Resource has been renamed. ResourceName: "What?", PropertyName: "What_"
        string What_ { get; }
        /// <summary>
        /// <para>5</para>
        /// </summary>
        string Equals { get; }
        /// <summary>
        /// <para>int value</para>
        /// </summary>
        string @int { get; }
        /// <summary>
        /// <para>str1</para>
        /// </summary>
        string String1 { get; }
        global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.Resource.IString2 String2 { get; }
        /// <summary>
        /// <para>&lt;1&gt;</para>
        /// </summary>
#warning Resource has been renamed. ResourceName: "<11>", PropertyName: "__11_"
        string __11_ { get; }
    }
}

namespace Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.Resource
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator.Generator", "1.0.0.0")]
    internal interface Iha_h_a2 : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>7</para>
        /// </summary>
        string a { get; }
        global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.Resource.ha_h_a2.Ib b { get; }
    }
}

namespace Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.Resource.ha_h_a2
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator.Generator", "1.0.0.0")]
    internal interface Ib : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>8</para>
        /// </summary>
        string c { get; }
        global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.Resource.ha_h_a2.b.Ihaha3 haha3 { get; }
    }
}

namespace Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.Resource.ha_h_a2.b
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator.Generator", "1.0.0.0")]
    internal interface Ihaha3 : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>//9</para>
        /// </summary>
        string cc { get; }
    }
}

namespace Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.Resource
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator.Generator", "1.0.0.0")]
    internal interface Itest : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// </summary>
        string test { get; }
    }
}

namespace Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.Resource
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator.Generator", "1.0.0.0")]
    internal interface IGetValue : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>Va</para>
        /// </summary>
        new string GetValue { get; }
    }
}

namespace Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.Resource
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator.Generator", "1.0.0.0")]
    internal interface Idouble : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>string of double</para>
        /// </summary>
        string @string { get; }
    }
}

namespace Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.Resource
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator.Generator", "1.0.0.0")]
    internal interface IString2 : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.Resource.String2.Iaa aa { get; }
    }
}

namespace Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.Resource.String2
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator.Generator", "1.0.0.0")]
    internal interface Iaa : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>2</para>
        /// </summary>
#warning Resource has been renamed. ResourceName: "1", PropertyName: "_1"
        string _1 { get; }
        /// <summary>
        /// <para>3</para>
        /// </summary>
        string bb { get; }
    }
}

namespace Opportunity.ResourceGenerator.TestApp
{
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator.Generator", "1.0.0.0")]
    internal static class Strings
    {

        internal static global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.IResource Resource { get; } = new global::Opportunity.ResourceGenerator.TestApp.Strings.Resource__SBC0AcXn();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator.Generator", "1.0.0.0")]
        [global::System.Diagnostics.DebuggerDisplay("[ms-resource:///Resource]")]
        private sealed class Resource__SBC0AcXn : global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.IResource
        {
            global::Opportunity.ResourceGenerator.GeneratedResourceProvider global::Opportunity.ResourceGenerator.IResourceProvider.this[string resourceKey]
            {
                get
                {
                    if(resourceKey == null)
                        throw new global::System.ArgumentNullException();
                    return new global::Opportunity.ResourceGenerator.GeneratedResourceProvider("ms-resource:///Resource/" + resourceKey);
                }
            }

            string global::Opportunity.ResourceGenerator.IResourceProvider.GetValue(string resourceKey)
            {
                return global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/" + resourceKey);
            }


            global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.Resource.Iha_h_a2 global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.IResource.ha_h_a2 { get; } = new global::Opportunity.ResourceGenerator.TestApp.Strings.Resource__SBC0AcXn.ha_h_a2__ozQj5Zxf();

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator.Generator", "1.0.0.0")]
            [global::System.Diagnostics.DebuggerDisplay("[ms-resource:///Resource/ha.h\"a2]", Name = "ha_h_a2")]
            private sealed class ha_h_a2__ozQj5Zxf : global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.Resource.Iha_h_a2
            {
                global::Opportunity.ResourceGenerator.GeneratedResourceProvider global::Opportunity.ResourceGenerator.IResourceProvider.this[string resourceKey]
                {
                    get
                    {
                        if(resourceKey == null)
                            throw new global::System.ArgumentNullException();
                        return new global::Opportunity.ResourceGenerator.GeneratedResourceProvider("ms-resource:///Resource/ha.h\"a2/" + resourceKey);
                    }
                }

                string global::Opportunity.ResourceGenerator.IResourceProvider.GetValue(string resourceKey)
                {
                    if(resourceKey == null)
                        return global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/ha.h\"a2");
                    return global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/ha.h\"a2/" + resourceKey);
                }

                global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.Resource.ha_h_a2.Ib global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.Resource.Iha_h_a2.b { get; } = new global::Opportunity.ResourceGenerator.TestApp.Strings.Resource__SBC0AcXn.ha_h_a2__ozQj5Zxf.b__wuOfwE2R();

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator.Generator", "1.0.0.0")]
                [global::System.Diagnostics.DebuggerDisplay("[ms-resource:///Resource/ha.h\"a2/b]", Name = "b")]
                private sealed class b__wuOfwE2R : global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.Resource.ha_h_a2.Ib
                {
                    global::Opportunity.ResourceGenerator.GeneratedResourceProvider global::Opportunity.ResourceGenerator.IResourceProvider.this[string resourceKey]
                    {
                        get
                        {
                            if(resourceKey == null)
                                throw new global::System.ArgumentNullException();
                            return new global::Opportunity.ResourceGenerator.GeneratedResourceProvider("ms-resource:///Resource/ha.h\"a2/b/" + resourceKey);
                        }
                    }

                    string global::Opportunity.ResourceGenerator.IResourceProvider.GetValue(string resourceKey)
                    {
                        if(resourceKey == null)
                            return global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/ha.h\"a2/b");
                        return global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/ha.h\"a2/b/" + resourceKey);
                    }

                    global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.Resource.ha_h_a2.b.Ihaha3 global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.Resource.ha_h_a2.Ib.haha3 { get; } = new global::Opportunity.ResourceGenerator.TestApp.Strings.Resource__SBC0AcXn.ha_h_a2__ozQj5Zxf.b__wuOfwE2R.haha3__bpeIdfHJ();

                    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator.Generator", "1.0.0.0")]
                    [global::System.Diagnostics.DebuggerDisplay("[ms-resource:///Resource/ha.h\"a2/b/haha3]", Name = "haha3")]
                    private sealed class haha3__bpeIdfHJ : global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.Resource.ha_h_a2.b.Ihaha3
                    {
                        global::Opportunity.ResourceGenerator.GeneratedResourceProvider global::Opportunity.ResourceGenerator.IResourceProvider.this[string resourceKey]
                        {
                            get
                            {
                                if(resourceKey == null)
                                    throw new global::System.ArgumentNullException();
                                return new global::Opportunity.ResourceGenerator.GeneratedResourceProvider("ms-resource:///Resource/ha.h\"a2/b/haha3/" + resourceKey);
                            }
                        }

                        string global::Opportunity.ResourceGenerator.IResourceProvider.GetValue(string resourceKey)
                        {
                            if(resourceKey == null)
                                return global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/ha.h\"a2/b/haha3");
                            return global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/ha.h\"a2/b/haha3/" + resourceKey);
                        }

                        string global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.Resource.ha_h_a2.b.Ihaha3.cc
                            => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/ha.h\"a2/b/haha3/cc");
                    }

                    string global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.Resource.ha_h_a2.Ib.c
                        => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/ha.h\"a2/b/c");
                }

                string global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.Resource.Iha_h_a2.a
                    => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/ha.h\"a2/a");
            }

            global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.Resource.Itest global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.IResource.test { get; } = new global::Opportunity.ResourceGenerator.TestApp.Strings.Resource__SBC0AcXn.test__SMOpIZsm();

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator.Generator", "1.0.0.0")]
            [global::System.Diagnostics.DebuggerDisplay("[ms-resource:///Resource/test]", Name = "test")]
            private sealed class test__SMOpIZsm : global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.Resource.Itest
            {
                global::Opportunity.ResourceGenerator.GeneratedResourceProvider global::Opportunity.ResourceGenerator.IResourceProvider.this[string resourceKey]
                {
                    get
                    {
                        if(resourceKey == null)
                            throw new global::System.ArgumentNullException();
                        return new global::Opportunity.ResourceGenerator.GeneratedResourceProvider("ms-resource:///Resource/test/" + resourceKey);
                    }
                }

                string global::Opportunity.ResourceGenerator.IResourceProvider.GetValue(string resourceKey)
                {
                    if(resourceKey == null)
                        return global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/test");
                    return global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/test/" + resourceKey);
                }

                string global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.Resource.Itest.test
                    => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/test/test");
            }

            global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.Resource.IGetValue global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.IResource.GetValue { get; } = new global::Opportunity.ResourceGenerator.TestApp.Strings.Resource__SBC0AcXn.GetValue__CZ2prM7A();

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator.Generator", "1.0.0.0")]
            [global::System.Diagnostics.DebuggerDisplay("[ms-resource:///Resource/GetValue]", Name = "GetValue")]
            private sealed class GetValue__CZ2prM7A : global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.Resource.IGetValue
            {
                global::Opportunity.ResourceGenerator.GeneratedResourceProvider global::Opportunity.ResourceGenerator.IResourceProvider.this[string resourceKey]
                {
                    get
                    {
                        if(resourceKey == null)
                            throw new global::System.ArgumentNullException();
                        return new global::Opportunity.ResourceGenerator.GeneratedResourceProvider("ms-resource:///Resource/GetValue/" + resourceKey);
                    }
                }

                string global::Opportunity.ResourceGenerator.IResourceProvider.GetValue(string resourceKey)
                {
                    if(resourceKey == null)
                        return global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/GetValue");
                    return global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/GetValue/" + resourceKey);
                }

                string global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.Resource.IGetValue.GetValue
                    => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/GetValue/GetValue");
            }

            global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.Resource.Idouble global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.IResource.@double { get; } = new global::Opportunity.ResourceGenerator.TestApp.Strings.Resource__SBC0AcXn.double__gXxSfEHf();

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator.Generator", "1.0.0.0")]
            [global::System.Diagnostics.DebuggerDisplay("[ms-resource:///Resource/double]", Name = "@double")]
            private sealed class double__gXxSfEHf : global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.Resource.Idouble
            {
                global::Opportunity.ResourceGenerator.GeneratedResourceProvider global::Opportunity.ResourceGenerator.IResourceProvider.this[string resourceKey]
                {
                    get
                    {
                        if(resourceKey == null)
                            throw new global::System.ArgumentNullException();
                        return new global::Opportunity.ResourceGenerator.GeneratedResourceProvider("ms-resource:///Resource/double/" + resourceKey);
                    }
                }

                string global::Opportunity.ResourceGenerator.IResourceProvider.GetValue(string resourceKey)
                {
                    if(resourceKey == null)
                        return global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/double");
                    return global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/double/" + resourceKey);
                }

                string global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.Resource.Idouble.@string
                    => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/double/string");
            }

            global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.Resource.IString2 global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.IResource.String2 { get; } = new global::Opportunity.ResourceGenerator.TestApp.Strings.Resource__SBC0AcXn.String2__26QOh7VS();

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator.Generator", "1.0.0.0")]
            [global::System.Diagnostics.DebuggerDisplay("[ms-resource:///Resource/String2]", Name = "String2")]
            private sealed class String2__26QOh7VS : global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.Resource.IString2
            {
                global::Opportunity.ResourceGenerator.GeneratedResourceProvider global::Opportunity.ResourceGenerator.IResourceProvider.this[string resourceKey]
                {
                    get
                    {
                        if(resourceKey == null)
                            throw new global::System.ArgumentNullException();
                        return new global::Opportunity.ResourceGenerator.GeneratedResourceProvider("ms-resource:///Resource/String2/" + resourceKey);
                    }
                }

                string global::Opportunity.ResourceGenerator.IResourceProvider.GetValue(string resourceKey)
                {
                    if(resourceKey == null)
                        return global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/String2");
                    return global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/String2/" + resourceKey);
                }

                global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.Resource.String2.Iaa global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.Resource.IString2.aa { get; } = new global::Opportunity.ResourceGenerator.TestApp.Strings.Resource__SBC0AcXn.String2__26QOh7VS.aa__pvHXZQGd();

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator.Generator", "1.0.0.0")]
                [global::System.Diagnostics.DebuggerDisplay("[ms-resource:///Resource/String2/aa]", Name = "aa")]
                private sealed class aa__pvHXZQGd : global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.Resource.String2.Iaa
                {
                    global::Opportunity.ResourceGenerator.GeneratedResourceProvider global::Opportunity.ResourceGenerator.IResourceProvider.this[string resourceKey]
                    {
                        get
                        {
                            if(resourceKey == null)
                                throw new global::System.ArgumentNullException();
                            return new global::Opportunity.ResourceGenerator.GeneratedResourceProvider("ms-resource:///Resource/String2/aa/" + resourceKey);
                        }
                    }

                    string global::Opportunity.ResourceGenerator.IResourceProvider.GetValue(string resourceKey)
                    {
                        if(resourceKey == null)
                            return global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/String2/aa");
                        return global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/String2/aa/" + resourceKey);
                    }

                    string global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.Resource.String2.Iaa._1
                        => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/String2/aa/1");
                    string global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.Resource.String2.Iaa.bb
                        => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/String2/aa/bb");
                }

            }

            string global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.IResource.ha_ha
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/ha\"ha");
            string global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.IResource._haha
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/_haha");
            string global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.IResource.__
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/\t");
            string global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.IResource.Reset
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/Reset");
            string global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.IResource.MemberwiseClone
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/MemberwiseClone");
            string global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.IResource.ReferenceEquals
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/ReferenceEquals");
            string global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.IResource.GetType
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/GetType");
            string global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.IResource.GetHashCode
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/GetHashCode");
            string global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.IResource.What_
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/What?");
            string global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.IResource.Equals
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/Equals");
            string global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.IResource.@int
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/int");
            string global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.IResource.String1
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/String1");
            string global::Opportunity.ResourceGenerator.TestApp.Opportunity.ResourceGenerator.TestApp_ResourceInfo.IResource.__11_
                => global::Opportunity.ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/<11>");
        }
    }
}
