version: Build - {build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- cmd: >-
    nuget restore

    msbuild "Opportunity.ResourceGenerator.Generator/Opportunity.ResourceGenerator.Generator.csproj" /property:Configuration=Release;Platform=AnyCPU /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
build:
  project: /Opportunity.ResourceGenerator/
  verbosity: minimal
after_build:
- cmd: nuget pack "Opportunity.ResourceGenerator/Opportunity.ResourceGenerator.nuspec" -OutputDirectory "packagegenerate"
artifacts:
- path: /packagegenerate/*.nupkg
  name: Nuget Package
deploy:
- provider: NuGet
  api_key:
    secure: cbXUaBDDi9qM2CTeRS/V71WRe56ZsjZGLBPBOlzsX0e1oSRV9L5R/qLYMQNaun9N
  skip_symbols: false
  on:
    branch: master