#pragma checksum "C:\Users\liuzh\Source\Repos\ResourceGenerator\Strings\en\Resource.resw" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "C2F317E5BF5498B15C002BD416A22A50"
#pragma checksum "C:\Users\liuzh\Source\Repos\ResourceGenerator\Strings\en\Resource.resJson" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "D5D4E8EBFA1D561EF977ABDFE7139499"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceGenerator.ResourceGenerator_ResourceInfo
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Resource Generator", "2.0.3.0")]
    internal interface IResourceProvider
    {
        global::ResourceGenerator.ResourceGenerator_ResourceInfo.GeneratedResourceProvider this[string resourceKey] { get; }
        string GetValue(string resourceKey);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Resource Generator", "2.0.3.0")]
    [global::System.Diagnostics.DebuggerDisplay("[{key,nq}] = {Value}")]
    internal struct GeneratedResourceProvider : global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResourceProvider
    {
        internal GeneratedResourceProvider(string key)
        {
            this.key = key;
        }

        [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
        private readonly string key;

        public string Value => global::ResourceGenerator.LocalizedStrings.GetValue(key);

        public GeneratedResourceProvider this[string resourceKey]
        {
            get
            {
                if(resourceKey == null)
                    throw new global::System.ArgumentNullException();
                return new global::ResourceGenerator.ResourceGenerator_ResourceInfo.GeneratedResourceProvider($"{key}/{resourceKey}");
            }
        }

        public string GetValue(string resourceKey)
        {
            if(resourceKey == null)
                return this.Value;
            return global::ResourceGenerator.LocalizedStrings.GetValue($"{key}/{resourceKey}");
        }
    }
}

namespace ResourceGenerator.ResourceGenerator_ResourceInfo
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Resource Generator", "2.0.3.0")]
    internal interface IResource : global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResourceProvider
    {
        /// <summary>
        /// <para>Eq</para>
        /// </summary>
        string Equals { get; }
        /// <summary>
        /// <para>int value</para>
        /// </summary>
        string @int { get; }
        /// <summary>
        /// <para>str1</para>
        /// </summary>
        string String1 { get; }
        global::ResourceGenerator.ResourceGenerator_ResourceInfo.Resource.IString2 String2 { get; }
        /// <summary>
        /// <para>&lt;1&gt;</para>
        /// </summary>
#warning Resource has been renamed. ResourceName: "<11>", PropertyName: "__11_"
        string __11_ { get; }
        /// <summary>
        /// <para>6</para>
        /// </summary>
#warning Resource has been renamed. ResourceName: "ha\"ha", PropertyName: "ha_ha"
        string ha_ha { get; }
#warning Resource has been renamed. ResourceName: "ha.h\"a2", PropertyName: "ha_h_a2"
        global::ResourceGenerator.ResourceGenerator_ResourceInfo.Resource.Iha_h_a2 ha_h_a2 { get; }
        /// <summary>
        /// </summary>
#warning Resource has been renamed. ResourceName: "\t", PropertyName: "__"
        string __ { get; }
        global::ResourceGenerator.ResourceGenerator_ResourceInfo.Resource.Itest test { get; }
        /// <summary>
        /// <para>Re</para>
        /// </summary>
        string Reset { get; }
        /// <summary>
        /// <para>MC</para>
        /// </summary>
        string MemberwiseClone { get; }
        /// <summary>
        /// <para>REq</para>
        /// </summary>
        string ReferenceEquals { get; }
        /// <summary>
        /// <para>GT</para>
        /// </summary>
        string GetType { get; }
        /// <summary>
        /// <para>GHC</para>
        /// </summary>
        string GetHashCode { get; }
        new global::ResourceGenerator.ResourceGenerator_ResourceInfo.Resource.IGetValue GetValue { get; }
        global::ResourceGenerator.ResourceGenerator_ResourceInfo.Resource.Idouble @double { get; }
        /// <summary>
        /// <para>A question mark?</para>
        /// </summary>
#warning Resource has been renamed. ResourceName: "What?", PropertyName: "What_"
        string What_ { get; }
    }
}

namespace ResourceGenerator.ResourceGenerator_ResourceInfo.Resource
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Resource Generator", "2.0.3.0")]
    internal interface IString2 : global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResourceProvider
    {
        global::ResourceGenerator.ResourceGenerator_ResourceInfo.Resource.String2.Iaa aa { get; }
    }
}

namespace ResourceGenerator.ResourceGenerator_ResourceInfo.Resource.String2
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Resource Generator", "2.0.3.0")]
    internal interface Iaa : global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResourceProvider
    {
        /// <summary>
        /// <para>3</para>
        /// </summary>
        string bb { get; }
    }
}

namespace ResourceGenerator.ResourceGenerator_ResourceInfo.Resource
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Resource Generator", "2.0.3.0")]
    internal interface Iha_h_a2 : global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResourceProvider
    {
        /// <summary>
        /// <para>7</para>
        /// </summary>
        string a { get; }
        global::ResourceGenerator.ResourceGenerator_ResourceInfo.Resource.ha_h_a2.Ib b { get; }
    }
}

namespace ResourceGenerator.ResourceGenerator_ResourceInfo.Resource.ha_h_a2
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Resource Generator", "2.0.3.0")]
    internal interface Ib : global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResourceProvider
    {
        /// <summary>
        /// <para>8</para>
        /// </summary>
        string c { get; }
        global::ResourceGenerator.ResourceGenerator_ResourceInfo.Resource.ha_h_a2.b.Ihaha3 haha3 { get; }
    }
}

namespace ResourceGenerator.ResourceGenerator_ResourceInfo.Resource.ha_h_a2.b
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Resource Generator", "2.0.3.0")]
    internal interface Ihaha3 : global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResourceProvider
    {
        /// <summary>
        /// <para>//9</para>
        /// </summary>
        string cc { get; }
    }
}

namespace ResourceGenerator.ResourceGenerator_ResourceInfo.Resource
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Resource Generator", "2.0.3.0")]
    internal interface Itest : global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResourceProvider
    {
#warning Resource has been renamed. ResourceName: "", PropertyName: "__Empty__"
        global::ResourceGenerator.ResourceGenerator_ResourceInfo.Resource.test.I__Empty__ __Empty__ { get; }
    }
}

namespace ResourceGenerator.ResourceGenerator_ResourceInfo.Resource.test
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Resource Generator", "2.0.3.0")]
    internal interface I__Empty__ : global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResourceProvider
    {
        /// <summary>
        /// </summary>
        string test { get; }
    }
}

namespace ResourceGenerator.ResourceGenerator_ResourceInfo.Resource
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Resource Generator", "2.0.3.0")]
    internal interface IGetValue : global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResourceProvider
    {
        /// <summary>
        /// <para>Va</para>
        /// </summary>
        new string GetValue { get; }
    }
}

namespace ResourceGenerator.ResourceGenerator_ResourceInfo.Resource
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Resource Generator", "2.0.3.0")]
    internal interface Idouble : global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResourceProvider
    {
        /// <summary>
        /// <para>string of double</para>
        /// </summary>
        string @string { get; }
    }
}

namespace ResourceGenerator
{
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Resource Generator", "2.0.3.0")]
    internal static class LocalizedStrings
    {
        private static readonly global::System.Collections.Generic.IDictionary<string, string> __cache__6pS6XhSb
            = new global::System.Collections.Generic.Dictionary<string, string>();
        private static readonly global::Windows.ApplicationModel.Resources.ResourceLoader __loader__ODiGbid9
            = global::Windows.ApplicationModel.Resources.ResourceLoader.GetForViewIndependentUse();

        internal static string GetValue(string resourceKey)
        {
            string value;
            if(global::ResourceGenerator.LocalizedStrings.__cache__6pS6XhSb.TryGetValue(resourceKey, out value))
                return value;
            string escaped = resourceKey.Replace("%", "%25").Replace("?", "%3F").Replace("#", "%23").Replace("*", "%2A").Replace("\"", "%22");
            return global::ResourceGenerator.LocalizedStrings.__cache__6pS6XhSb[resourceKey] = global::ResourceGenerator.LocalizedStrings.__loader__ODiGbid9.GetString(escaped);
        }


        internal static global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResource Resource { get; } = new global::ResourceGenerator.LocalizedStrings.Resource__ZrbM_ile();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Resource Generator", "2.0.3.0")]
        [global::System.Diagnostics.DebuggerDisplay("[ms-resource:///Resource]")]
        private sealed class Resource__ZrbM_ile : global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResource
        {
            global::ResourceGenerator.ResourceGenerator_ResourceInfo.GeneratedResourceProvider global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResourceProvider.this[string resourceKey]
            {
                get
                {
                    if(resourceKey == null)
                        throw new global::System.ArgumentNullException();
                    return new global::ResourceGenerator.ResourceGenerator_ResourceInfo.GeneratedResourceProvider("ms-resource:///Resource/" + resourceKey);
                }
            }

            string global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResourceProvider.GetValue(string resourceKey)
            {
                return global::ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/" + resourceKey);
            }


            global::ResourceGenerator.ResourceGenerator_ResourceInfo.Resource.IString2 global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResource.String2 { get; } = new global::ResourceGenerator.LocalizedStrings.Resource__ZrbM_ile.String2__EIZ1crsm();

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Resource Generator", "2.0.3.0")]
            [global::System.Diagnostics.DebuggerDisplay("[ms-resource:///Resource/String2]", Name = "String2")]
            private sealed class String2__EIZ1crsm : global::ResourceGenerator.ResourceGenerator_ResourceInfo.Resource.IString2
            {
                global::ResourceGenerator.ResourceGenerator_ResourceInfo.GeneratedResourceProvider global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResourceProvider.this[string resourceKey]
                {
                    get
                    {
                        if(resourceKey == null)
                            throw new global::System.ArgumentNullException();
                        return new global::ResourceGenerator.ResourceGenerator_ResourceInfo.GeneratedResourceProvider("ms-resource:///Resource/String2/" + resourceKey);
                    }
                }

                string global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResourceProvider.GetValue(string resourceKey)
                {
                    if(resourceKey == null)
                        return global::ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/String2");
                    return global::ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/String2/" + resourceKey);
                }

                global::ResourceGenerator.ResourceGenerator_ResourceInfo.Resource.String2.Iaa global::ResourceGenerator.ResourceGenerator_ResourceInfo.Resource.IString2.aa { get; } = new global::ResourceGenerator.LocalizedStrings.Resource__ZrbM_ile.String2__EIZ1crsm.aa__dn_L1wLp();

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Resource Generator", "2.0.3.0")]
                [global::System.Diagnostics.DebuggerDisplay("[ms-resource:///Resource/String2/aa]", Name = "aa")]
                private sealed class aa__dn_L1wLp : global::ResourceGenerator.ResourceGenerator_ResourceInfo.Resource.String2.Iaa
                {
                    global::ResourceGenerator.ResourceGenerator_ResourceInfo.GeneratedResourceProvider global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResourceProvider.this[string resourceKey]
                    {
                        get
                        {
                            if(resourceKey == null)
                                throw new global::System.ArgumentNullException();
                            return new global::ResourceGenerator.ResourceGenerator_ResourceInfo.GeneratedResourceProvider("ms-resource:///Resource/String2/aa/" + resourceKey);
                        }
                    }

                    string global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResourceProvider.GetValue(string resourceKey)
                    {
                        if(resourceKey == null)
                            return global::ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/String2/aa");
                        return global::ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/String2/aa/" + resourceKey);
                    }

                    string global::ResourceGenerator.ResourceGenerator_ResourceInfo.Resource.String2.Iaa.bb
                        => global::ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/String2/aa/bb");
                }

            }

            global::ResourceGenerator.ResourceGenerator_ResourceInfo.Resource.Iha_h_a2 global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResource.ha_h_a2 { get; } = new global::ResourceGenerator.LocalizedStrings.Resource__ZrbM_ile.ha_h_a2__erHtSu6j();

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Resource Generator", "2.0.3.0")]
            [global::System.Diagnostics.DebuggerDisplay("[ms-resource:///Resource/ha.h\"a2]", Name = "ha_h_a2")]
            private sealed class ha_h_a2__erHtSu6j : global::ResourceGenerator.ResourceGenerator_ResourceInfo.Resource.Iha_h_a2
            {
                global::ResourceGenerator.ResourceGenerator_ResourceInfo.GeneratedResourceProvider global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResourceProvider.this[string resourceKey]
                {
                    get
                    {
                        if(resourceKey == null)
                            throw new global::System.ArgumentNullException();
                        return new global::ResourceGenerator.ResourceGenerator_ResourceInfo.GeneratedResourceProvider("ms-resource:///Resource/ha.h\"a2/" + resourceKey);
                    }
                }

                string global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResourceProvider.GetValue(string resourceKey)
                {
                    if(resourceKey == null)
                        return global::ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/ha.h\"a2");
                    return global::ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/ha.h\"a2/" + resourceKey);
                }

                global::ResourceGenerator.ResourceGenerator_ResourceInfo.Resource.ha_h_a2.Ib global::ResourceGenerator.ResourceGenerator_ResourceInfo.Resource.Iha_h_a2.b { get; } = new global::ResourceGenerator.LocalizedStrings.Resource__ZrbM_ile.ha_h_a2__erHtSu6j.b__WRpDpPlT();

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Resource Generator", "2.0.3.0")]
                [global::System.Diagnostics.DebuggerDisplay("[ms-resource:///Resource/ha.h\"a2/b]", Name = "b")]
                private sealed class b__WRpDpPlT : global::ResourceGenerator.ResourceGenerator_ResourceInfo.Resource.ha_h_a2.Ib
                {
                    global::ResourceGenerator.ResourceGenerator_ResourceInfo.GeneratedResourceProvider global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResourceProvider.this[string resourceKey]
                    {
                        get
                        {
                            if(resourceKey == null)
                                throw new global::System.ArgumentNullException();
                            return new global::ResourceGenerator.ResourceGenerator_ResourceInfo.GeneratedResourceProvider("ms-resource:///Resource/ha.h\"a2/b/" + resourceKey);
                        }
                    }

                    string global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResourceProvider.GetValue(string resourceKey)
                    {
                        if(resourceKey == null)
                            return global::ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/ha.h\"a2/b");
                        return global::ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/ha.h\"a2/b/" + resourceKey);
                    }

                    global::ResourceGenerator.ResourceGenerator_ResourceInfo.Resource.ha_h_a2.b.Ihaha3 global::ResourceGenerator.ResourceGenerator_ResourceInfo.Resource.ha_h_a2.Ib.haha3 { get; } = new global::ResourceGenerator.LocalizedStrings.Resource__ZrbM_ile.ha_h_a2__erHtSu6j.b__WRpDpPlT.haha3__EfJEZJTy();

                    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Resource Generator", "2.0.3.0")]
                    [global::System.Diagnostics.DebuggerDisplay("[ms-resource:///Resource/ha.h\"a2/b/haha3]", Name = "haha3")]
                    private sealed class haha3__EfJEZJTy : global::ResourceGenerator.ResourceGenerator_ResourceInfo.Resource.ha_h_a2.b.Ihaha3
                    {
                        global::ResourceGenerator.ResourceGenerator_ResourceInfo.GeneratedResourceProvider global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResourceProvider.this[string resourceKey]
                        {
                            get
                            {
                                if(resourceKey == null)
                                    throw new global::System.ArgumentNullException();
                                return new global::ResourceGenerator.ResourceGenerator_ResourceInfo.GeneratedResourceProvider("ms-resource:///Resource/ha.h\"a2/b/haha3/" + resourceKey);
                            }
                        }

                        string global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResourceProvider.GetValue(string resourceKey)
                        {
                            if(resourceKey == null)
                                return global::ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/ha.h\"a2/b/haha3");
                            return global::ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/ha.h\"a2/b/haha3/" + resourceKey);
                        }

                        string global::ResourceGenerator.ResourceGenerator_ResourceInfo.Resource.ha_h_a2.b.Ihaha3.cc
                            => global::ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/ha.h\"a2/b/haha3/cc");
                    }

                    string global::ResourceGenerator.ResourceGenerator_ResourceInfo.Resource.ha_h_a2.Ib.c
                        => global::ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/ha.h\"a2/b/c");
                }

                string global::ResourceGenerator.ResourceGenerator_ResourceInfo.Resource.Iha_h_a2.a
                    => global::ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/ha.h\"a2/a");
            }

            global::ResourceGenerator.ResourceGenerator_ResourceInfo.Resource.Itest global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResource.test { get; } = new global::ResourceGenerator.LocalizedStrings.Resource__ZrbM_ile.test__M6kDu8Qm();

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Resource Generator", "2.0.3.0")]
            [global::System.Diagnostics.DebuggerDisplay("[ms-resource:///Resource/test]", Name = "test")]
            private sealed class test__M6kDu8Qm : global::ResourceGenerator.ResourceGenerator_ResourceInfo.Resource.Itest
            {
                global::ResourceGenerator.ResourceGenerator_ResourceInfo.GeneratedResourceProvider global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResourceProvider.this[string resourceKey]
                {
                    get
                    {
                        if(resourceKey == null)
                            throw new global::System.ArgumentNullException();
                        return new global::ResourceGenerator.ResourceGenerator_ResourceInfo.GeneratedResourceProvider("ms-resource:///Resource/test/" + resourceKey);
                    }
                }

                string global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResourceProvider.GetValue(string resourceKey)
                {
                    if(resourceKey == null)
                        return global::ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/test");
                    return global::ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/test/" + resourceKey);
                }

                global::ResourceGenerator.ResourceGenerator_ResourceInfo.Resource.test.I__Empty__ global::ResourceGenerator.ResourceGenerator_ResourceInfo.Resource.Itest.__Empty__ { get; } = new global::ResourceGenerator.LocalizedStrings.Resource__ZrbM_ile.test__M6kDu8Qm.__zTnPI71E();

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Resource Generator", "2.0.3.0")]
                [global::System.Diagnostics.DebuggerDisplay("[ms-resource:///Resource/test/]", Name = "__Empty__")]
                private sealed class __zTnPI71E : global::ResourceGenerator.ResourceGenerator_ResourceInfo.Resource.test.I__Empty__
                {
                    global::ResourceGenerator.ResourceGenerator_ResourceInfo.GeneratedResourceProvider global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResourceProvider.this[string resourceKey]
                    {
                        get
                        {
                            if(resourceKey == null)
                                throw new global::System.ArgumentNullException();
                            return new global::ResourceGenerator.ResourceGenerator_ResourceInfo.GeneratedResourceProvider("ms-resource:///Resource/test//" + resourceKey);
                        }
                    }

                    string global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResourceProvider.GetValue(string resourceKey)
                    {
                        if(resourceKey == null)
                            return global::ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/test/");
                        return global::ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/test//" + resourceKey);
                    }

                    string global::ResourceGenerator.ResourceGenerator_ResourceInfo.Resource.test.I__Empty__.test
                        => global::ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/test//test");
                }

            }

            global::ResourceGenerator.ResourceGenerator_ResourceInfo.Resource.IGetValue global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResource.GetValue { get; } = new global::ResourceGenerator.LocalizedStrings.Resource__ZrbM_ile.GetValue__yyrr4QQ7();

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Resource Generator", "2.0.3.0")]
            [global::System.Diagnostics.DebuggerDisplay("[ms-resource:///Resource/GetValue]", Name = "GetValue")]
            private sealed class GetValue__yyrr4QQ7 : global::ResourceGenerator.ResourceGenerator_ResourceInfo.Resource.IGetValue
            {
                global::ResourceGenerator.ResourceGenerator_ResourceInfo.GeneratedResourceProvider global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResourceProvider.this[string resourceKey]
                {
                    get
                    {
                        if(resourceKey == null)
                            throw new global::System.ArgumentNullException();
                        return new global::ResourceGenerator.ResourceGenerator_ResourceInfo.GeneratedResourceProvider("ms-resource:///Resource/GetValue/" + resourceKey);
                    }
                }

                string global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResourceProvider.GetValue(string resourceKey)
                {
                    if(resourceKey == null)
                        return global::ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/GetValue");
                    return global::ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/GetValue/" + resourceKey);
                }

                string global::ResourceGenerator.ResourceGenerator_ResourceInfo.Resource.IGetValue.GetValue
                    => global::ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/GetValue/GetValue");
            }

            global::ResourceGenerator.ResourceGenerator_ResourceInfo.Resource.Idouble global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResource.@double { get; } = new global::ResourceGenerator.LocalizedStrings.Resource__ZrbM_ile.double__aNqR_a3_();

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Resource Generator", "2.0.3.0")]
            [global::System.Diagnostics.DebuggerDisplay("[ms-resource:///Resource/double]", Name = "@double")]
            private sealed class double__aNqR_a3_ : global::ResourceGenerator.ResourceGenerator_ResourceInfo.Resource.Idouble
            {
                global::ResourceGenerator.ResourceGenerator_ResourceInfo.GeneratedResourceProvider global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResourceProvider.this[string resourceKey]
                {
                    get
                    {
                        if(resourceKey == null)
                            throw new global::System.ArgumentNullException();
                        return new global::ResourceGenerator.ResourceGenerator_ResourceInfo.GeneratedResourceProvider("ms-resource:///Resource/double/" + resourceKey);
                    }
                }

                string global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResourceProvider.GetValue(string resourceKey)
                {
                    if(resourceKey == null)
                        return global::ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/double");
                    return global::ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/double/" + resourceKey);
                }

                string global::ResourceGenerator.ResourceGenerator_ResourceInfo.Resource.Idouble.@string
                    => global::ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/double/string");
            }

            string global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResource.Equals
                => global::ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/Equals");
            string global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResource.@int
                => global::ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/int");
            string global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResource.String1
                => global::ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/String1");
            string global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResource.__11_
                => global::ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/<11>");
            string global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResource.ha_ha
                => global::ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/ha\"ha");
            string global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResource.__
                => global::ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/\t");
            string global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResource.Reset
                => global::ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/Reset");
            string global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResource.MemberwiseClone
                => global::ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/MemberwiseClone");
            string global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResource.ReferenceEquals
                => global::ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/ReferenceEquals");
            string global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResource.GetType
                => global::ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/GetType");
            string global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResource.GetHashCode
                => global::ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/GetHashCode");
            string global::ResourceGenerator.ResourceGenerator_ResourceInfo.IResource.What_
                => global::ResourceGenerator.LocalizedStrings.GetValue("ms-resource:///Resource/What?");
        }
    }
}
