#ExternalChecksum ("C:\Users\lzy\Documents\Source\ResourceGenerator\Opportunity.ResourceGenerator.TestApp.VB\Strings\en\Resource.resJson", "{406ea660-64cf-4c82-b6f0-42d48172a799}", "20FF98CF5D68DBA3EF210285AEC55DCA")
#ExternalChecksum ("C:\Users\lzy\Documents\Source\ResourceGenerator\Opportunity.ResourceGenerator.TestApp.VB\Strings\en\Resource.resw", "{406ea660-64cf-4c82-b6f0-42d48172a799}", "F8BA5D4ABE46A24FADCCA0C5F75C32E2")
#ExternalChecksum ("C:\Users\lzy\Documents\Source\ResourceGenerator\Opportunity.ResourceGenerator.TestApp.VB\Strings\en\Resources.resJson", "{406ea660-64cf-4c82-b6f0-42d48172a799}", "8B7629AF6CD356FFDE60191D64E39C00")
'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace ResourceInfo

    '''<summary><para>Path: ms-resource:///Resource</para></summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0")>
    Friend Interface IResource
        Inherits Global.Opportunity.ResourceGenerator.IResourceProvider

        '''<summary><para>Path: ms-resource:///Resource/QuatationMark&quot;Test</para><para>Value:</para><para>Test &quot;</para></summary>
        ReadOnly Property QuatationMark_Test() As String

        '''<summary><para>Path: ms-resource:///Resource/QuatationMark&quot;And.DotTest</para></summary>
        ReadOnly Property QuatationMark_And_DotTest() As Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.Resource.IQuatationMark_And_DotTest

        '''<summary><para>Path: ms-resource:///Resource/Contains_underscore</para><para>Value:</para><para>contains _</para></summary>
        ReadOnly Property Contains_underscore() As String

        '''<summary><para>Path: ms-resource:///Resource/test</para></summary>
        ReadOnly Property test() As Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.Resource.Itest

        '''<summary><para>Path: ms-resource:///Resource/Reset</para><para>Value:</para><para>Speicial name Reset</para></summary>
        ReadOnly Property Reset() As String

        '''<summary><para>Path: ms-resource:///Resource/**</para><para>Value:</para><para>Speicial name **</para></summary>
        ReadOnly Property ___() As String

        '''<summary><para>Path: ms-resource:///Resource/MemberwiseClone</para><para>Value:</para><para>Speicial name MemberwiseClone</para></summary>
        ReadOnly Property MemberwiseClone() As String

        '''<summary><para>Path: ms-resource:///Resource/ReferenceEquals</para><para>Value:</para><para>Speicial name ReferenceEquals</para></summary>
        ReadOnly Property ReferenceEquals() As String

        '''<summary><para>Path: ms-resource:///Resource/GetType</para><para>Value:</para><para>Speicial name GetType</para></summary>
        ReadOnly Property [GetType]() As String

        '''<summary><para>Path: ms-resource:///Resource/GetHashCode</para><para>Value:</para><para>Speicial name GetHashCode</para></summary>
        ReadOnly Property GetHashCode() As String

        '''<summary><para>Path: ms-resource:///Resource/GetValue</para></summary>
        ReadOnly Property GetValue() As Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.Resource.IGetValue

        '''<summary><para>Path: ms-resource:///Resource/double</para></summary>
        ReadOnly Property [double]() As Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.Resource.Idouble

        '''<summary><para>Path: ms-resource:///Resource/What?</para><para>Value:</para><para>Question mark test What?</para></summary>
        ReadOnly Property What_() As String

        '''<summary><para>Path: ms-resource:///Resource/Space Test</para><para>Value:</para><para>Space test</para></summary>
        ReadOnly Property Space_Test() As String

        '''<summary><para>Path: ms-resource:///Resource/ StartWithSpace</para><para>Value:</para><para>start with space</para></summary>
        ReadOnly Property __StartWithSpace() As String

        '''<summary><para>Path: ms-resource:///Resource/EndWithSpace </para><para>Value:</para><para>end with space</para></summary>
        ReadOnly Property EndWithSpace_() As String

        '''<summary><para>Path: ms-resource:///Resource/ </para></summary>
        ReadOnly Property __() As Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.Resource.I__

        '''<summary><para>Path: ms-resource:///Resource/Plus+Test</para><para>Value:</para><para>+</para></summary>
        ReadOnly Property Plus_Test() As String

        '''<summary><para>Path: ms-resource:///Resource/Equals</para><para>Value:</para><para>Speical name Equals</para></summary>
        ReadOnly Property Equals() As String

        '''<summary><para>Path: ms-resource:///Resource/int</para><para>Value:</para><para>keyword int</para></summary>
        ReadOnly Property int() As String

        '''<summary><para>Path: ms-resource:///Resource/String1</para><para>Value:</para><para>str1</para></summary>
        ReadOnly Property String1() As String

        '''<summary><para>Path: ms-resource:///Resource/String2</para></summary>
        ReadOnly Property String2() As Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.Resource.IString2

        '''<summary><para>Path: ms-resource:///Resource/&lt;11&gt;</para><para>Value:</para><para>Completely invalid name in c# &quot;&lt;11&gt;&quot;</para></summary>
        ReadOnly Property __11_() As String

        '''<summary><para>Path: ms-resource:///Resource/_StartWithUnderscoreInResw</para><para>Value:</para><para>Starts With - In Resw</para></summary>
        ReadOnly Property _StartWithUnderscoreInResw() As String

        '''<summary><para>Path: ms-resource:///Resource/$FormatJson</para><para>Value:</para><para>{Path} = {null}</para></summary>
        Function FormatJson() As Global.Opportunity.ResourceGenerator.FormattableResourceString

        '''<summary><para>Path: ms-resource:///Resource/$FormatJson</para><para>Value:</para><para>{Path} = {null}</para></summary>
        Function FormatJson(ByVal Path As Object, ByVal null As Object) As String

        '''<summary><para>Path: ms-resource:///Resource/$FormatJson</para><para>Value:</para><para>{Path} = {null}</para></summary>
        Function FormatJson(ByVal provider As Global.System.IFormatProvider, ByVal Path As Object, ByVal null As Object) As String

        '''<summary><para>Path: ms-resource:///Resource/$FormatString</para><para>Value:</para><para>{Name} = {Value}</para></summary>
        Function FormatString() As Global.Opportunity.ResourceGenerator.FormattableResourceString

        '''<summary><para>Path: ms-resource:///Resource/$FormatString</para><para>Value:</para><para>{Name} = {Value}</para></summary>
        Function FormatString(ByVal Name As Object, ByVal Value As Object) As String

        '''<summary><para>Path: ms-resource:///Resource/$FormatString</para><para>Value:</para><para>{Name} = {Value}</para></summary>
        Function FormatString(ByVal provider As Global.System.IFormatProvider, ByVal Name As Object, ByVal Value As Object) As String
    End Interface

    '''<summary><para>Path: ms-resource:///Resources</para></summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0")>
    Friend Interface IResources
        Inherits Global.Opportunity.ResourceGenerator.IResourceProvider

        '''<summary><para>Path: ms-resource:///Resources/AppName</para><para>Value:</para><para>TestName</para></summary>
        ReadOnly Property AppName() As String
    End Interface
End Namespace

Namespace ResourceInfo.Resource

    '''<summary><para>Path: ms-resource:///Resource/QuatationMark&quot;And.DotTest</para></summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0")>
    Friend Interface IQuatationMark_And_DotTest
        Inherits Global.Opportunity.ResourceGenerator.IResourceProvider

        '''<summary><para>Path: ms-resource:///Resource/QuatationMark&quot;And.DotTest/SubItem1</para><para>Value:</para><para>sub 1</para></summary>
        ReadOnly Property SubItem1() As String

        '''<summary><para>Path: ms-resource:///Resource/QuatationMark&quot;And.DotTest/SubItem2</para></summary>
        ReadOnly Property SubItem2() As Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.Resource.QuatationMark_And_DotTest.ISubItem2
    End Interface

    '''<summary><para>Path: ms-resource:///Resource/test</para></summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0")>
    Friend Interface Itest
        Inherits Global.Opportunity.ResourceGenerator.IResourceProvider

        '''<summary><para>Path: ms-resource:///Resource/test/test</para><para>Value:</para><para>path of test/test without object</para></summary>
        ReadOnly Property test() As String
    End Interface

    '''<summary><para>Path: ms-resource:///Resource/GetValue</para></summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0")>
    Friend Interface IGetValue
        Inherits Global.Opportunity.ResourceGenerator.IResourceProvider

        '''<summary><para>Path: ms-resource:///Resource/GetValue/GetValue</para><para>Value:</para><para>GetValue in GetValue object</para></summary>
        ReadOnly Property GetValue() As String
    End Interface

    '''<summary><para>Path: ms-resource:///Resource/double</para></summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0")>
    Friend Interface Idouble
        Inherits Global.Opportunity.ResourceGenerator.IResourceProvider

        '''<summary><para>Path: ms-resource:///Resource/double/string</para><para>Value:</para><para>keyword test double/string</para></summary>
        ReadOnly Property [string]() As String
    End Interface

    '''<summary><para>Path: ms-resource:///Resource/ </para></summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0")>
    Friend Interface I__
        Inherits Global.Opportunity.ResourceGenerator.IResourceProvider

        '''<summary><para>Path: ms-resource:///Resource/ / </para><para>Value:</para><para>Space and space</para></summary>
        ReadOnly Property __() As String
    End Interface

    '''<summary><para>Path: ms-resource:///Resource/String2</para></summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0")>
    Friend Interface IString2
        Inherits Global.Opportunity.ResourceGenerator.IResourceProvider

        '''<summary><para>Path: ms-resource:///Resource/String2/aa</para></summary>
        ReadOnly Property aa() As Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.Resource.String2.Iaa
    End Interface
End Namespace

Namespace ResourceInfo.Resource.QuatationMark_And_DotTest

    '''<summary><para>Path: ms-resource:///Resource/QuatationMark&quot;And.DotTest/SubItem2</para></summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0")>
    Friend Interface ISubItem2
        Inherits Global.Opportunity.ResourceGenerator.IResourceProvider

        '''<summary><para>Path: ms-resource:///Resource/QuatationMark&quot;And.DotTest/SubItem2/SubSubItem1</para><para>Value:</para><para>sub sub 1</para></summary>
        ReadOnly Property SubSubItem1() As String

        '''<summary><para>Path: ms-resource:///Resource/QuatationMark&quot;And.DotTest/SubItem2/SubSubItem2</para></summary>
        ReadOnly Property SubSubItem2() As Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.Resource.QuatationMark_And_DotTest.SubItem2.ISubSubItem2
    End Interface
End Namespace

Namespace ResourceInfo.Resource.QuatationMark_And_DotTest.SubItem2

    '''<summary><para>Path: ms-resource:///Resource/QuatationMark&quot;And.DotTest/SubItem2/SubSubItem2</para></summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0")>
    Friend Interface ISubSubItem2
        Inherits Global.Opportunity.ResourceGenerator.IResourceProvider

        '''<summary><para>Path: ms-resource:///Resource/QuatationMark&quot;And.DotTest/SubItem2/SubSubItem2/WithPath</para><para>Value:</para><para>sub sub 2 / path</para></summary>
        ReadOnly Property WithPath() As String
    End Interface
End Namespace

Namespace ResourceInfo.Resource.String2

    '''<summary><para>Path: ms-resource:///Resource/String2/aa</para></summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0")>
    Friend Interface Iaa
        Inherits Global.Opportunity.ResourceGenerator.IResourceProvider

        '''<summary><para>Path: ms-resource:///Resource/String2/aa/1</para><para>Value:</para><para>str2.aa.1</para></summary>
        ReadOnly Property _1() As String

        '''<summary><para>Path: ms-resource:///Resource/String2/aa/bb</para><para>Value:</para><para>str2.aa.bb</para></summary>
        ReadOnly Property bb() As String
    End Interface
End Namespace


<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0"),
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
Friend NotInheritable Class Strings

    Private Shared s_Resource__qPEfl_9K As Global.Opportunity.ResourceGenerator.TestApp.VB.Strings.Resource__QNqyoh8_

    Private Shared s_QuatationMark_And_DotTest__kpWvWpkS As Global.Opportunity.ResourceGenerator.TestApp.VB.Strings.QuatationMark_And_DotTest__TjTMjRVw

    Private Shared s_SubItem2__6BBREXDh As Global.Opportunity.ResourceGenerator.TestApp.VB.Strings.SubItem2__DG47dyUk

    Private Shared s_SubSubItem2__pKJLAnuY As Global.Opportunity.ResourceGenerator.TestApp.VB.Strings.SubSubItem2__QNoG9XkX

    Private Shared s_test__tOZBn5ax As Global.Opportunity.ResourceGenerator.TestApp.VB.Strings.test__QLP4H_oG

    Private Shared s_GetValue___DzE60w7 As Global.Opportunity.ResourceGenerator.TestApp.VB.Strings.GetValue__BDHL_q_u

    Private Shared s_double__xwnyojZy As Global.Opportunity.ResourceGenerator.TestApp.VB.Strings.double__aZ0bl7b2

    Private Shared s_____oKFEVfBI As Global.Opportunity.ResourceGenerator.TestApp.VB.Strings.____LMkWSlyJ

    Private Shared s_String2__1FRmvLVc As Global.Opportunity.ResourceGenerator.TestApp.VB.Strings.String2__TKnzXQk_

    Private Shared s_aa__vmH6Wc7l As Global.Opportunity.ResourceGenerator.TestApp.VB.Strings.aa__6xwwStiM

    Private Shared s_Resources__9xSs00sM As Global.Opportunity.ResourceGenerator.TestApp.VB.Strings.Resources__2K3fOkqr

    Private Sub New()
        MyBase.New
    End Sub

    Friend Shared ReadOnly Property Resource() As Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.IResource
        Get
            Return System.Threading.LazyInitializer.EnsureInitialized(Of Global.Opportunity.ResourceGenerator.TestApp.VB.Strings.Resource__QNqyoh8_)(Global.Opportunity.ResourceGenerator.TestApp.VB.Strings.s_Resource__qPEfl_9K)
        End Get
    End Property

    Friend Shared ReadOnly Property Resources() As Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.IResources
        Get
            Return System.Threading.LazyInitializer.EnsureInitialized(Of Global.Opportunity.ResourceGenerator.TestApp.VB.Strings.Resources__2K3fOkqr)(Global.Opportunity.ResourceGenerator.TestApp.VB.Strings.s_Resources__9xSs00sM)
        End Get
    End Property

    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0")>
    Private NotInheritable Class Resource__QNqyoh8_
        Inherits Global.Opportunity.ResourceGenerator.ResourceProviderBase
        Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.IResource

        Private Shared FormatJson__A2n_s87h As Global.Opportunity.ResourceGenerator.FormattableResourceString = New Global.Opportunity.ResourceGenerator.FormattableResourceString(Global.Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resource/$FormatJson"))

        Private Shared FormatString__DG8TuV9A As Global.Opportunity.ResourceGenerator.FormattableResourceString = New Global.Opportunity.ResourceGenerator.FormattableResourceString(Global.Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resource/$FormatString"))

        Public Sub New()
            MyBase.New("ms-resource:///Resource/")
        End Sub

        <Global.Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resource/QuatationMark""Test")>
        ReadOnly Property Global_Opportunity_ResourceGenerator_TestApp_VB_ResourceInfo_IResource_QuatationMark_Test() As String Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.IResource.QuatationMark_Test
            Get
                Return Global.Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resource/QuatationMark""Test")
            End Get
        End Property

        <Global.Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resource/QuatationMark""And.DotTest")>
        ReadOnly Property Global_Opportunity_ResourceGenerator_TestApp_VB_ResourceInfo_IResource_QuatationMark_And_DotTest() As Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.Resource.IQuatationMark_And_DotTest Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.IResource.QuatationMark_And_DotTest
            Get
                Return System.Threading.LazyInitializer.EnsureInitialized(Of Global.Opportunity.ResourceGenerator.TestApp.VB.Strings.QuatationMark_And_DotTest__TjTMjRVw)(Global.Opportunity.ResourceGenerator.TestApp.VB.Strings.s_QuatationMark_And_DotTest__kpWvWpkS)
            End Get
        End Property

        <Global.Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resource/Contains_underscore")>
        ReadOnly Property Global_Opportunity_ResourceGenerator_TestApp_VB_ResourceInfo_IResource_Contains_underscore() As String Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.IResource.Contains_underscore
            Get
                Return Global.Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resource/Contains_underscore")
            End Get
        End Property

        <Global.Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resource/test")>
        ReadOnly Property Global_Opportunity_ResourceGenerator_TestApp_VB_ResourceInfo_IResource_test() As Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.Resource.Itest Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.IResource.test
            Get
                Return System.Threading.LazyInitializer.EnsureInitialized(Of Global.Opportunity.ResourceGenerator.TestApp.VB.Strings.test__QLP4H_oG)(Global.Opportunity.ResourceGenerator.TestApp.VB.Strings.s_test__tOZBn5ax)
            End Get
        End Property

        <Global.Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resource/Reset")>
        ReadOnly Property Global_Opportunity_ResourceGenerator_TestApp_VB_ResourceInfo_IResource_Reset() As String Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.IResource.Reset
            Get
                Return Global.Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resource/Reset")
            End Get
        End Property

        <Global.Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resource/**")>
        ReadOnly Property Global_Opportunity_ResourceGenerator_TestApp_VB_ResourceInfo_IResource____() As String Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.IResource.___
            Get
                Return Global.Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resource/**")
            End Get
        End Property

        <Global.Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resource/MemberwiseClone")>
        ReadOnly Property Global_Opportunity_ResourceGenerator_TestApp_VB_ResourceInfo_IResource_MemberwiseClone() As String Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.IResource.MemberwiseClone
            Get
                Return Global.Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resource/MemberwiseClone")
            End Get
        End Property

        <Global.Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resource/ReferenceEquals")>
        ReadOnly Property Global_Opportunity_ResourceGenerator_TestApp_VB_ResourceInfo_IResource_ReferenceEquals() As String Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.IResource.ReferenceEquals
            Get
                Return Global.Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resource/ReferenceEquals")
            End Get
        End Property

        <Global.Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resource/GetType")>
        ReadOnly Property Global_Opportunity_ResourceGenerator_TestApp_VB_ResourceInfo_IResource_GetType() As String Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.IResource.[GetType]
            Get
                Return Global.Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resource/GetType")
            End Get
        End Property

        <Global.Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resource/GetHashCode")>
        ReadOnly Property Global_Opportunity_ResourceGenerator_TestApp_VB_ResourceInfo_IResource_GetHashCode() As String Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.IResource.GetHashCode
            Get
                Return Global.Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resource/GetHashCode")
            End Get
        End Property

        <Global.Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resource/GetValue")>
        ReadOnly Property Global_Opportunity_ResourceGenerator_TestApp_VB_ResourceInfo_IResource_GetValue() As Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.Resource.IGetValue Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.IResource.GetValue
            Get
                Return System.Threading.LazyInitializer.EnsureInitialized(Of Global.Opportunity.ResourceGenerator.TestApp.VB.Strings.GetValue__BDHL_q_u)(Global.Opportunity.ResourceGenerator.TestApp.VB.Strings.s_GetValue___DzE60w7)
            End Get
        End Property

        <Global.Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resource/double")>
        ReadOnly Property Global_Opportunity_ResourceGenerator_TestApp_VB_ResourceInfo_IResource_double() As Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.Resource.Idouble Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.IResource.[double]
            Get
                Return System.Threading.LazyInitializer.EnsureInitialized(Of Global.Opportunity.ResourceGenerator.TestApp.VB.Strings.double__aZ0bl7b2)(Global.Opportunity.ResourceGenerator.TestApp.VB.Strings.s_double__xwnyojZy)
            End Get
        End Property

        <Global.Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resource/What?")>
        ReadOnly Property Global_Opportunity_ResourceGenerator_TestApp_VB_ResourceInfo_IResource_What_() As String Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.IResource.What_
            Get
                Return Global.Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resource/What?")
            End Get
        End Property

        <Global.Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resource/Space Test")>
        ReadOnly Property Global_Opportunity_ResourceGenerator_TestApp_VB_ResourceInfo_IResource_Space_Test() As String Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.IResource.Space_Test
            Get
                Return Global.Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resource/Space Test")
            End Get
        End Property

        <Global.Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resource/ StartWithSpace")>
        ReadOnly Property Global_Opportunity_ResourceGenerator_TestApp_VB_ResourceInfo_IResource___StartWithSpace() As String Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.IResource.__StartWithSpace
            Get
                Return Global.Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resource/ StartWithSpace")
            End Get
        End Property

        <Global.Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resource/EndWithSpace ")>
        ReadOnly Property Global_Opportunity_ResourceGenerator_TestApp_VB_ResourceInfo_IResource_EndWithSpace_() As String Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.IResource.EndWithSpace_
            Get
                Return Global.Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resource/EndWithSpace ")
            End Get
        End Property

        <Global.Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resource/ ")>
        ReadOnly Property Global_Opportunity_ResourceGenerator_TestApp_VB_ResourceInfo_IResource___() As Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.Resource.I__ Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.IResource.__
            Get
                Return System.Threading.LazyInitializer.EnsureInitialized(Of Global.Opportunity.ResourceGenerator.TestApp.VB.Strings.____LMkWSlyJ)(Global.Opportunity.ResourceGenerator.TestApp.VB.Strings.s_____oKFEVfBI)
            End Get
        End Property

        <Global.Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resource/Plus+Test")>
        ReadOnly Property Global_Opportunity_ResourceGenerator_TestApp_VB_ResourceInfo_IResource_Plus_Test() As String Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.IResource.Plus_Test
            Get
                Return Global.Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resource/Plus+Test")
            End Get
        End Property

        <Global.Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resource/Equals")>
        ReadOnly Property Global_Opportunity_ResourceGenerator_TestApp_VB_ResourceInfo_IResource_Equals() As String Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.IResource.Equals
            Get
                Return Global.Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resource/Equals")
            End Get
        End Property

        <Global.Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resource/int")>
        ReadOnly Property Global_Opportunity_ResourceGenerator_TestApp_VB_ResourceInfo_IResource_int() As String Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.IResource.int
            Get
                Return Global.Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resource/int")
            End Get
        End Property

        <Global.Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resource/String1")>
        ReadOnly Property Global_Opportunity_ResourceGenerator_TestApp_VB_ResourceInfo_IResource_String1() As String Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.IResource.String1
            Get
                Return Global.Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resource/String1")
            End Get
        End Property

        <Global.Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resource/String2")>
        ReadOnly Property Global_Opportunity_ResourceGenerator_TestApp_VB_ResourceInfo_IResource_String2() As Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.Resource.IString2 Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.IResource.String2
            Get
                Return System.Threading.LazyInitializer.EnsureInitialized(Of Global.Opportunity.ResourceGenerator.TestApp.VB.Strings.String2__TKnzXQk_)(Global.Opportunity.ResourceGenerator.TestApp.VB.Strings.s_String2__1FRmvLVc)
            End Get
        End Property

        <Global.Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resource/<11>")>
        ReadOnly Property Global_Opportunity_ResourceGenerator_TestApp_VB_ResourceInfo_IResource___11_() As String Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.IResource.__11_
            Get
                Return Global.Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resource/<11>")
            End Get
        End Property

        <Global.Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resource/_StartWithUnderscoreInResw")>
        ReadOnly Property Global_Opportunity_ResourceGenerator_TestApp_VB_ResourceInfo_IResource__StartWithUnderscoreInResw() As String Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.IResource._StartWithUnderscoreInResw
            Get
                Return Global.Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resource/_StartWithUnderscoreInResw")
            End Get
        End Property

        <Global.Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resource/$FormatJson")>
        Function Global_Opportunity_ResourceGenerator_TestApp_VB_ResourceInfo_IResource_FormatJson() As Global.Opportunity.ResourceGenerator.FormattableResourceString Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.IResource.FormatJson
            Return Global.Opportunity.ResourceGenerator.TestApp.VB.Strings.Resource__QNqyoh8_.FormatJson__A2n_s87h
        End Function

        Function Global_Opportunity_ResourceGenerator_TestApp_VB_ResourceInfo_IResource_FormatJson(ByVal Path As Object, ByVal null As Object) As String Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.IResource.FormatJson
            Return String.Format(Global.Opportunity.ResourceGenerator.TestApp.VB.Strings.Resource__QNqyoh8_.FormatJson__A2n_s87h.FormatString, null, Path)
        End Function

        Function Global_Opportunity_ResourceGenerator_TestApp_VB_ResourceInfo_IResource_FormatJson(ByVal provider As Global.System.IFormatProvider, ByVal Path As Object, ByVal null As Object) As String Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.IResource.FormatJson
            Return String.Format(Global.Opportunity.ResourceGenerator.TestApp.VB.Strings.Resource__QNqyoh8_.FormatJson__A2n_s87h.FormatString, provider, null, Path)
        End Function

        <Global.Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resource/$FormatString")>
        Function Global_Opportunity_ResourceGenerator_TestApp_VB_ResourceInfo_IResource_FormatString() As Global.Opportunity.ResourceGenerator.FormattableResourceString Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.IResource.FormatString
            Return Global.Opportunity.ResourceGenerator.TestApp.VB.Strings.Resource__QNqyoh8_.FormatString__DG8TuV9A
        End Function

        Function Global_Opportunity_ResourceGenerator_TestApp_VB_ResourceInfo_IResource_FormatString(ByVal Name As Object, ByVal Value As Object) As String Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.IResource.FormatString
            Return String.Format(Global.Opportunity.ResourceGenerator.TestApp.VB.Strings.Resource__QNqyoh8_.FormatString__DG8TuV9A.FormatString, Name, Value)
        End Function

        Function Global_Opportunity_ResourceGenerator_TestApp_VB_ResourceInfo_IResource_FormatString(ByVal provider As Global.System.IFormatProvider, ByVal Name As Object, ByVal Value As Object) As String Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.IResource.FormatString
            Return String.Format(Global.Opportunity.ResourceGenerator.TestApp.VB.Strings.Resource__QNqyoh8_.FormatString__DG8TuV9A.FormatString, provider, Name, Value)
        End Function
    End Class

    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0")>
    Private NotInheritable Class QuatationMark_And_DotTest__TjTMjRVw
        Inherits Global.Opportunity.ResourceGenerator.ResourceProviderBase
        Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.Resource.IQuatationMark_And_DotTest

        Public Sub New()
            MyBase.New("ms-resource:///Resource/QuatationMark""And.DotTest/")
        End Sub

        <Global.Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resource/QuatationMark""And.DotTest/SubItem1")>
        ReadOnly Property Global_Opportunity_ResourceGenerator_TestApp_VB_ResourceInfo_Resource_IQuatationMark_And_DotTest_SubItem1() As String Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.Resource.IQuatationMark_And_DotTest.SubItem1
            Get
                Return Global.Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resource/QuatationMark""And.DotTest/SubItem1")
            End Get
        End Property

        <Global.Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resource/QuatationMark""And.DotTest/SubItem2")>
        ReadOnly Property Global_Opportunity_ResourceGenerator_TestApp_VB_ResourceInfo_Resource_IQuatationMark_And_DotTest_SubItem2() As Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.Resource.QuatationMark_And_DotTest.ISubItem2 Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.Resource.IQuatationMark_And_DotTest.SubItem2
            Get
                Return System.Threading.LazyInitializer.EnsureInitialized(Of Global.Opportunity.ResourceGenerator.TestApp.VB.Strings.SubItem2__DG47dyUk)(Global.Opportunity.ResourceGenerator.TestApp.VB.Strings.s_SubItem2__6BBREXDh)
            End Get
        End Property
    End Class

    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0")>
    Private NotInheritable Class SubItem2__DG47dyUk
        Inherits Global.Opportunity.ResourceGenerator.ResourceProviderBase
        Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.Resource.QuatationMark_And_DotTest.ISubItem2

        Public Sub New()
            MyBase.New("ms-resource:///Resource/QuatationMark""And.DotTest/SubItem2/")
        End Sub

        <Global.Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resource/QuatationMark""And.DotTest/SubItem2/SubSubItem1")>
        ReadOnly Property Global_Opportunity_ResourceGenerator_TestApp_VB_ResourceInfo_Resource_QuatationMark_And_DotTest_ISubItem2_SubSubItem1() As String Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.Resource.QuatationMark_And_DotTest.ISubItem2.SubSubItem1
            Get
                Return Global.Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resource/QuatationMark""And.DotTest/SubItem2/SubSubItem1")
            End Get
        End Property

        <Global.Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resource/QuatationMark""And.DotTest/SubItem2/SubSubItem2")>
        ReadOnly Property Global_Opportunity_ResourceGenerator_TestApp_VB_ResourceInfo_Resource_QuatationMark_And_DotTest_ISubItem2_SubSubItem2() As Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.Resource.QuatationMark_And_DotTest.SubItem2.ISubSubItem2 Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.Resource.QuatationMark_And_DotTest.ISubItem2.SubSubItem2
            Get
                Return System.Threading.LazyInitializer.EnsureInitialized(Of Global.Opportunity.ResourceGenerator.TestApp.VB.Strings.SubSubItem2__QNoG9XkX)(Global.Opportunity.ResourceGenerator.TestApp.VB.Strings.s_SubSubItem2__pKJLAnuY)
            End Get
        End Property
    End Class

    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0")>
    Private NotInheritable Class SubSubItem2__QNoG9XkX
        Inherits Global.Opportunity.ResourceGenerator.ResourceProviderBase
        Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.Resource.QuatationMark_And_DotTest.SubItem2.ISubSubItem2

        Public Sub New()
            MyBase.New("ms-resource:///Resource/QuatationMark""And.DotTest/SubItem2/SubSubItem2/")
        End Sub

        <Global.Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resource/QuatationMark""And.DotTest/SubItem2/SubSubItem2/WithPath")>
        ReadOnly Property Global_Opportunity_ResourceGenerator_TestApp_VB_ResourceInfo_Resource_QuatationMark_And_DotTest_SubItem2_ISubSubItem2_WithPath() As String Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.Resource.QuatationMark_And_DotTest.SubItem2.ISubSubItem2.WithPath
            Get
                Return Global.Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resource/QuatationMark""And.DotTest/SubItem2/SubSubItem2/WithPath")
            End Get
        End Property
    End Class

    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0")>
    Private NotInheritable Class test__QLP4H_oG
        Inherits Global.Opportunity.ResourceGenerator.ResourceProviderBase
        Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.Resource.Itest

        Public Sub New()
            MyBase.New("ms-resource:///Resource/test/")
        End Sub

        <Global.Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resource/test/test")>
        ReadOnly Property Global_Opportunity_ResourceGenerator_TestApp_VB_ResourceInfo_Resource_Itest_test() As String Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.Resource.Itest.test
            Get
                Return Global.Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resource/test/test")
            End Get
        End Property
    End Class

    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0")>
    Private NotInheritable Class GetValue__BDHL_q_u
        Inherits Global.Opportunity.ResourceGenerator.ResourceProviderBase
        Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.Resource.IGetValue

        Public Sub New()
            MyBase.New("ms-resource:///Resource/GetValue/")
        End Sub

        <Global.Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resource/GetValue/GetValue")>
        ReadOnly Property Global_Opportunity_ResourceGenerator_TestApp_VB_ResourceInfo_Resource_IGetValue_GetValue() As String Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.Resource.IGetValue.GetValue
            Get
                Return Global.Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resource/GetValue/GetValue")
            End Get
        End Property
    End Class

    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0")>
    Private NotInheritable Class double__aZ0bl7b2
        Inherits Global.Opportunity.ResourceGenerator.ResourceProviderBase
        Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.Resource.Idouble

        Public Sub New()
            MyBase.New("ms-resource:///Resource/double/")
        End Sub

        <Global.Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resource/double/string")>
        ReadOnly Property Global_Opportunity_ResourceGenerator_TestApp_VB_ResourceInfo_Resource_Idouble_string() As String Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.Resource.Idouble.[string]
            Get
                Return Global.Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resource/double/string")
            End Get
        End Property
    End Class

    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0")>
    Private NotInheritable Class ____LMkWSlyJ
        Inherits Global.Opportunity.ResourceGenerator.ResourceProviderBase
        Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.Resource.I__

        Public Sub New()
            MyBase.New("ms-resource:///Resource/ /")
        End Sub

        <Global.Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resource/ / ")>
        ReadOnly Property Global_Opportunity_ResourceGenerator_TestApp_VB_ResourceInfo_Resource_I_____() As String Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.Resource.I__.__
            Get
                Return Global.Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resource/ / ")
            End Get
        End Property
    End Class

    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0")>
    Private NotInheritable Class String2__TKnzXQk_
        Inherits Global.Opportunity.ResourceGenerator.ResourceProviderBase
        Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.Resource.IString2

        Public Sub New()
            MyBase.New("ms-resource:///Resource/String2/")
        End Sub

        <Global.Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resource/String2/aa")>
        ReadOnly Property Global_Opportunity_ResourceGenerator_TestApp_VB_ResourceInfo_Resource_IString2_aa() As Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.Resource.String2.Iaa Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.Resource.IString2.aa
            Get
                Return System.Threading.LazyInitializer.EnsureInitialized(Of Global.Opportunity.ResourceGenerator.TestApp.VB.Strings.aa__6xwwStiM)(Global.Opportunity.ResourceGenerator.TestApp.VB.Strings.s_aa__vmH6Wc7l)
            End Get
        End Property
    End Class

    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0")>
    Private NotInheritable Class aa__6xwwStiM
        Inherits Global.Opportunity.ResourceGenerator.ResourceProviderBase
        Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.Resource.String2.Iaa

        Public Sub New()
            MyBase.New("ms-resource:///Resource/String2/aa/")
        End Sub

        <Global.Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resource/String2/aa/1")>
        ReadOnly Property Global_Opportunity_ResourceGenerator_TestApp_VB_ResourceInfo_Resource_String2_Iaa__1() As String Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.Resource.String2.Iaa._1
            Get
                Return Global.Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resource/String2/aa/1")
            End Get
        End Property

        <Global.Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resource/String2/aa/bb")>
        ReadOnly Property Global_Opportunity_ResourceGenerator_TestApp_VB_ResourceInfo_Resource_String2_Iaa_bb() As String Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.Resource.String2.Iaa.bb
            Get
                Return Global.Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resource/String2/aa/bb")
            End Get
        End Property
    End Class

    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.4.0.0")>
    Private NotInheritable Class Resources__2K3fOkqr
        Inherits Global.Opportunity.ResourceGenerator.ResourceProviderBase
        Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.IResources

        Public Sub New()
            MyBase.New("ms-resource:///Resources/")
        End Sub

        <Global.Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/AppName")>
        ReadOnly Property Global_Opportunity_ResourceGenerator_TestApp_VB_ResourceInfo_IResources_AppName() As String Implements Global.Opportunity.ResourceGenerator.TestApp.VB.ResourceInfo.IResources.AppName
            Get
                Return Global.Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/AppName")
            End Get
        End Property
    End Class
End Class
